### ISSUE TITLE
Need endpoint for live/archived fixtures

### ISSUE THREAD

**Issue by emosGambler** [iwko/notifball-api#14]
Currently our application just shows scheduled fixtures. We need to have endpoint for exposing live/archived fixtures, so that user could see live/archived fixture results.

Brief:
* Expose `/fixtures/live` and `/fixture/archived` endpoints

**Comment by iwko** [comment]
@emosGambler I propose to add live matches to `/fixtures` endpoint. So this endpoint will return matches from now and future. And another endpoint for ended matches `fixutres/archived`

**Comment by iwko** [comment]
@emosGambler endpoint for finished fixtures added. https://github.com/iwko/notifball-api/pull/15 resolves it
